// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"
import mock "github.com/stretchr/testify/mock"

// GinRepo is an autogenerated mock type for the GinRepo type
type GinRepo struct {
	mock.Mock
}

// Register provides a mock function with given fields: withTemplate
func (_m *GinRepo) Register(withTemplate bool) (*gin.Engine, error) {
	ret := _m.Called(withTemplate)

	var r0 *gin.Engine
	if rf, ok := ret.Get(0).(func(bool) *gin.Engine); ok {
		r0 = rf(withTemplate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gin.Engine)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bool) error); ok {
		r1 = rf(withTemplate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetPath provides a mock function with given fields: newPath
func (_m *GinRepo) SetPath(newPath string) error {
	ret := _m.Called(newPath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(newPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
